version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres-r2dbc
    restart: unless-stopped

    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d mydb" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: